name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nimble-version: 5f4d8dc925b00c69a38d39958638040f3904e707
      test-command: |
        nimble setup -l
        nimble test
