name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nimble-version: 4efcb9477f383880cc2219f90f04ab1e8d3fe352
      test-command: |
        nimble setup -l
        nimble test
