name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nimble-version: 94179a0a46fcf2659dba34cf2384144dae65ec12
      test-command: |
        nimble setup -l
        nimble test
